-- MySQL Script generated by MySQL Workbench
-- vr 28 mei 2021 21:12:53 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dckingdoms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dckingdoms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dckingdoms` DEFAULT CHARACTER SET utf8 ;
USE `dckingdoms` ;

-- -----------------------------------------------------
-- Table `dckingdoms`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `server_id` BIGINT NULL DEFAULT NULL,
  `owner_id` BIGINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`kingdom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`kingdom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `king_id` VARCHAR(45) NULL DEFAULT NULL,
  `workpower` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kingdom_game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_kingdom_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `dckingdoms`.`game` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kingdom_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_region_kingdom1_idx` (`kingdom_id` ASC) VISIBLE,
  CONSTRAINT `fk_region_kingdom1`
    FOREIGN KEY (`kingdom_id`)
    REFERENCES `dckingdoms`.`kingdom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`attack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`attack` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region_id` INT NULL DEFAULT NULL,
  `attacker_kingdom` INT NULL DEFAULT NULL,
  `defender_kingdom` INT NULL DEFAULT NULL,
  `attacker_strength` INT NULL DEFAULT NULL,
  `defender_strength` INT NULL DEFAULT NULL,
  `started` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attack_region1_idx` (`region_id` ASC) VISIBLE,
  INDEX `fk_attack_kingdom1_idx` (`attacker_kingdom` ASC) VISIBLE,
  INDEX `fk_attack_kingdom2_idx` (`defender_kingdom` ASC) VISIBLE,
  CONSTRAINT `fk_attack_kingdom1`
    FOREIGN KEY (`attacker_kingdom`)
    REFERENCES `dckingdoms`.`kingdom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attack_kingdom2`
    FOREIGN KEY (`defender_kingdom`)
    REFERENCES `dckingdoms`.`kingdom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attack_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `dckingdoms`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`religion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`religion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_religion_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_religion_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `dckingdoms`.`game` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`citizen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`citizen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kingdom_id` INT NULL DEFAULT NULL,
  `religion_id` INT NULL DEFAULT NULL,
  `userid` BIGINT NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `strength` INT NULL DEFAULT '0',
  `trained` DATETIME NULL DEFAULT NULL,
  `location` INT NULL DEFAULT NULL,
  `moved` DATETIME NULL DEFAULT NULL,
  `worked` DATETIME NULL DEFAULT NULL,
  `currency` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_citizen_kingdom1_idx` (`kingdom_id` ASC) VISIBLE,
  INDEX `fk_citizen_religion1_idx` (`religion_id` ASC) VISIBLE,
  INDEX `fk_citizen_region1_idx` (`location` ASC) VISIBLE,
  CONSTRAINT `fk_citizen_kingdom1`
    FOREIGN KEY (`kingdom_id`)
    REFERENCES `dckingdoms`.`kingdom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_citizen_region1`
    FOREIGN KEY (`location`)
    REFERENCES `dckingdoms`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_citizen_religion1`
    FOREIGN KEY (`religion_id`)
    REFERENCES `dckingdoms`.`religion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`religion_per_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`religion_per_region` (
  `region_id` INT NOT NULL,
  `religion_id` INT NOT NULL,
  `amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`region_id`, `religion_id`),
  INDEX `fk_religion_has_region_region1_idx` (`region_id` ASC) VISIBLE,
  INDEX `fk_religion_has_region_religion1_idx` (`religion_id` ASC) VISIBLE,
  CONSTRAINT `fk_religion_has_region_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `dckingdoms`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_religion_has_region_religion1`
    FOREIGN KEY (`religion_id`)
    REFERENCES `dckingdoms`.`religion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dckingdoms`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dckingdoms`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `citizen_id` INT NULL DEFAULT NULL,
  `stock_name` VARCHAR(45) NULL DEFAULT NULL,
  `amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stock_citizen1_idx` (`citizen_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_citizen1`
    FOREIGN KEY (`citizen_id`)
    REFERENCES `dckingdoms`.`citizen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

